import Head from 'next/head';
import Breadcrumb from '../components/Breadcrumb';
import Category from '../components/Category';
import NoData from '../components/NoData';
import { useQuery } from '@apollo/client';
import { GET_CATEGORIES } from '../utils/graphql';

export default function Home() {
  const { loading, error, data } = useQuery(GET_CATEGORIES);

  console.log(data);
  if (loading) return <h1>loading</h1>;
  if (error) return <h1>error</h1>;
  return (
    <div className='p-5'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Breadcrumb />
      <div className='w-full max-w-lg mx-auto space-y-5'>
        {data.getCategories.map((item) => (
          <Category key={item.id} item={item} />
        ))}
      </div>

      {/* <NoData>category</NoData> */}
    </div>
  );
}
